### ISSUE TITLE
Feed project data in database

### ISSUE THREAD

**Issue by Bwaim** [MalgoskaG/AwesomeApp#30]
Feed all the project info correctly.
The document name is <Track>_Px with x the project number : for example ABND_P1
Each project has these fields :
![image](https://user-images.githubusercontent.com/32247433/39397215-d6bdb4a4-4afb-11e8-95c4-a9d2974f4581.png)
If more informations is needed, write a comment here

**Comment by MalgoskaG** [comment]
ready
