### ISSUE TITLE
Format correctly the deadline in the Project list

### ISSUE THREAD

**Issue by Bwaim** [MalgoskaG/AwesomeApp#31]

**Comment by MalgoskaG** [comment]
this can be resolved in the adapter
===================================================
 override fun onBindViewHolder(holder: ViewHolder, position: Int) {
        holder.projectNameTxt?.text = projectsList[position].name

        val dateFormatter = SimpleDateFormat("MMM d yyyy", Locale.getDefault())
        val formatedData = "Deadline: ${dateFormatter.format(projectsList[position].deadline).toUpperCase()}"

        val test = projectsList[position].deadline

        holder.deadLineTxt?.text = formatedData
        holder.percentOfUsersTxt?.text = projectsList[position].nbUsers.toString()

        val intentToDetails = Intent(context, DetailsActivity::class.java)

        holder.itemView.setOnClickListener{
            intentToDetails.putExtra(WHICH_PROJECT, projectsList[position].name)
            intentToDetails.putExtra(WHICH_TRACT, whichTrack)
            context.startActivity(intentToDetails)
        }
    }
